server:
  port: 9192

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:order
    username: sa
    password:
    driverClassName: org.h2.Driver

  application:
    name: ORDER-SERVICE